
package refugio_mascotas1;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;


public class Interfaz extends javax.swing.JFrame {
    
    
    /*
    
    //ArrayLists
    private ArrayList<Caninos> digimones = new ArrayList<>();
    private ArrayList<Felinos> pokemones = new ArrayList<>();
    
    //Metodo para agregar caninos
    public void agregarCanino() {
        
        //add lista con los objetos dentro
        digimones.add(new Caninos(JOptionPane.showInputDialog("Ingresar nombre"), 
                                    JOptionPane.showInputDialog("Ingresar raza"), 
                                    JOptionPane.showInputDialog("Ingresar color"), 
                                    Integer.parseInt(JOptionPane.showInputDialog("Ingresar edad")), 
                                    Integer.parseInt(JOptionPane.showInputDialog("Ingresar nivel de entrenamiento"))));
        
    }
    
    
    //Metodo para agregar felinos
    public void agregarFelino() {
        
        //add lista con los objetos dentro
        pokemones.add(new Felinos(JOptionPane.showInputDialog("Ingresar nombre"), 
                                    JOptionPane.showInputDialog("Ingresar raza"), 
                                    JOptionPane.showInputDialog("Ingresar color"), 
                                    Integer.parseInt(JOptionPane.showInputDialog("Ingresar edad")), 
                                    Boolean.parseBoolean(JOptionPane.showInputDialog("¿El felino se encuentra libre de Toxoplasmosis?"))));       
   
    }
    
    
    // "PATRON" Iterator para imprimir ArrayList -> Caninos
    Iterator dig = digimones.iterator();
    
    while (dig.hasNext){
    
}    
    
    /*
    
    
    
    
    /**
     * Creates new form Xvidos
     */
    public Interfaz() {
        initComponents();
    }
    
    private Datos b1 = new Datos();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        agregarButon = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Refugio animales");
        setIconImage(getIconImage());
        setResizable(false);

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tipo", "Nombre", "Raza", "Color", "Edad", "Entrenamiento", "Toxoplasmosis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDatos);

        agregarButon.setText("Agregar");
        agregarButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(agregarButon)
                        .addGap(106, 106, 106)
                        .addComponent(eliminarButton)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarButon)
                    .addComponent(eliminarButton))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButonActionPerformed
        // TODO add your handling code here:
        b1.agregarAnimal();
        actualizarTabla();
    }//GEN-LAST:event_agregarButonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:
        b1.eliminarAnimal();
        actualizarTabla();
    }//GEN-LAST:event_eliminarButtonActionPerformed

    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("refugio_mascotas1/download.jpeg"));


       return retValue;
    }
    private void actualizarTabla(){
        String[][] datos = new String[b1.getIdC() + b1.getIdF()][8];
        for (int i = 0; i < b1.getIdC(); i++) {
            datos[i][0] = b1.getDigimones().get(i).getId() + "";
            datos[i][1] = "canino";
            datos[i][2] = b1.getDigimones().get(i).getNombre();
            datos[i][3] = b1.getDigimones().get(i).getRaza();
            datos[i][4] = b1.getDigimones().get(i).getColor();
            datos[i][5] = b1.getDigimones().get(i).getEdad() + "";
            datos[i][6] = b1.getDigimones().get(i).getNivelE() + "";
            datos[i][7] = "no aplica";
        }
        for (int i = 0; i < b1.getIdF(); i++) {
            datos[i + b1.getIdC()][0] = b1.getPokemones().get(i).getId() + "";
            datos[i + b1.getIdC()][1] = "felino";
            datos[i + b1.getIdC()][2] = b1.getPokemones().get(i).getNombre();
            datos[i + b1.getIdC()][3] = b1.getPokemones().get(i).getRaza();
            datos[i + b1.getIdC()][4] = b1.getPokemones().get(i).getColor();
            datos[i + b1.getIdC()][5] = b1.getPokemones().get(i).getEdad() + "";
            datos[i + b1.getIdC()][6] = "no aplica";
            datos[i + b1.getIdC()][7] = b1.getPokemones().get(i).isToxo() + "";
        }
        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            datos,
            new String [] {
            "Id", "Tipo", "Nombre", "Raza", "Color", "Edad", "Entrenamiento", "Toxoplasmosis"
        }));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButon;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
